### ISSUE TITLE
Mention in the readme that there's no support for sha256 git repositories

### ISSUE THREAD

**Issue by jimboolio** [klandergren/jekyll-last-commit#2]
As the title says, mention somewhere that due to libgit2 limitations, sha256 repositories are not yet supported. Those are becoming more common and at least Forgejo/Codeberg seems to offer repository support already with the modern hashing algorithm.

**Comment by klandergren** [comment]
Thanks, addressed in https://github.com/klandergren/jekyll-last-commit/commit/ba3834cbc347198ed0f9e8316e09399f47f3e49e
